<?php
$lovers = [
    [
        "lastname" => "Doe",
        "firstname" => "John",
        "age" => "33 ans",
        "gender" => "homme",
        "mail" => "john.doe@google.com",
        "zipcode" => "80080",
        "picture" => "../assets/img/john-doe.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Martin",
        "firstname" => "Alice",
        "age" => "26 ans",
        "gender" => "femme",
        "mail" => "alice.martin@google.com",
        "zipcode" => "75020",
        "picture" => "../assets/img/alice-martin.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Carter",
        "firstname" => "Mark",
        "age" => "30 ans",
        "gender" => "homme",
        "mail" => "mark.carter@google.com",
        "zipcode" => "75002",
        "picture" => "../assets/img/mark-carter.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Guyon",
        "firstname" => "France",
        "age" => "25 ans",
        "gender" => "femme",
        "mail" => "france.guyon@google.com",
        "zipcode" => "67290",
        "picture" => "../assets/img/france-guyon.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Dage",
        "firstname" => "Jeremy",
        "age" => "23 ans",
        "gender" => "homme",
        "mail" => "jeremy.dage@google.com",
        "zipcode" => "80000",
        "picture" => "../assets/img/jeremy-dage.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Henry",
        "firstname" => "Margaux",
        "age" => "20 ans",
        "gender" => "femme",
        "mail" => "margaux.henry@google.com",
        "zipcode" => "60320",
        "picture" => "../assets/img/margaux-henry.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Croisé",
        "firstname" => "David",
        "age" => "27 ans",
        "gender" => "homme",
        "mail" => "david.croise@google.com",
        "zipcode" => "02500",
        "picture" => "../assets/img/david-croise.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Depres",
        "firstname" => "Pauline",
        "age" => "29 ans",
        "gender" => "femme",
        "mail" => "pauline.depres@google.com",
        "zipcode" => "80000",
        "picture" => "../assets/img/pauline-depres.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Bègue",
        "firstname" => "Maxime",
        "age" => "25 ans",
        "gender" => "hommz",
        "mail" => "maxime.begue@google.com",
        "zipcode" => "75019",
        "picture" => "../assets/img/maxime-begue.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Courrier",
        "firstname" => "Carole",
        "age" => "24 ans",
        "gender" => "femme",
        "mail" => "carole.courrier@google.com",
        "zipcode" => "80000",
        "picture" => "../assets/img/carole-courrier.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Deloin",
        "firstname" => "Henry",
        "age" => "34 ans",
        "gender" => "homme",
        "mail" => "henry.deloin@google.com",
        "zipcode" => "75016",
        "picture" => "../assets/img/henry-deloin.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Dubois",
        "firstname" => "Caroline",
        "age" => "22 ans",
        "gender" => "femme",
        "mail" => "caroline.dubois@google.com",
        "zipcode" => "60210",
        "picture" => "../assets/img/caroline-dubois.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Tiroir",
        "firstname" => "Josef",
        "age" => "35 ans",
        "gender" => "homme",
        "mail" => "josef.tiroir@google.com",
        "zipcode" => "80080",
        "picture" => "../assets/img/josef-tiroir.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Bleau",
        "firstname" => "Marta",
        "age" => "23 ans",
        "gender" => "femme",
        "mail" => "marta.bleau@google.com",
        "zipcode" => "75005",
        "picture" => "../assets/img/marta-bleau.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Guichard",
        "firstname" => "Morgan",
        "age" => "30 ans",
        "gender" => "homme",
        "mail" => "morgan.guichard@google.com",
        "zipcode" => "60000",
        "picture" => "../assets/img/morgan-guichard.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Tuile",
        "firstname" => "Carla",
        "age" => "30 ans",
        "gender" => "femme",
        "mail" => "carla.tuile@google.com",
        "zipcode" => "80000",
        "picture" => "../assets/img/carla-tuile.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Porte",
        "firstname" => "William",
        "age" => "36 ans",
        "gender" => "homme",
        "mail" => "william.porte@google.com",
        "zipcode" => "75004",
        "picture" => "../assets/img/william-porte.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Couturier",
        "firstname" => "Sandrine",
        "age" => "22 ans",
        "gender" => "femme",
        "mail" => "sandrine.couturier@google.com",
        "zipcode" => "80000",
        "picture" => "../assets/img/sandrine-couturier.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Salto",
        "firstname" => "Gregoire",
        "age" => "23 ans",
        "gender" => "homme",
        "mail" => "gregoire.salto@google.com",
        "zipcode" => "60000",
        "picture" => "../assets/img/gregoire-salto.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ],
    [
        "lastname" => "Cahier",
        "firstname" => "Martine",
        "age" => "28 ans",
        "gender" => "femme",
        "mail" => "martine.cahier@google.com",
        "zipcode" => "02000",
        "picture" => "../assets/img/martine-cahier.jpg",
        "description" => "Je cherche l'amour avec un grand A",
    ]
];
$loversToShow = [];
if (isset($_COOKIES["research_type"]) && !empty($_COOKIES["research_type"])) {
    foreach ($lovers as $lover) {
        if ($lover["gender"] === $_COOKIE["research_type"]) {
            array_push($loversToShow, $lover);
        }
    }
} else {
    $loversToShow = $lovers;
}
